server:
  port: 8080
  context-path: /cloudservice

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://106.52.169.209:9089/FGD?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: dy
    password: zhong1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybatisplus.dao.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
# logger
logging:
    config: classpath:log4j2_dev.xml
